name: Update Sponsors List

on:
  schedule:
    - cron: '0 0 * * 0' # every Sunday
  workflow_dispatch:

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Sponsors List
        uses: JamesIves/github-sponsors-readme-action@v1.0.5
