name: Update Sponsors List

on:
  schedule:
    - cron: '0 0 * * *' # daily
  workflow_dispatch:

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JamesIves/github-sponsors-readme-action@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: "README.md"
